const teamNames = {
    1: "Atlanta Hawks",
    2: "Boston Celtics",
    3: "Brooklyn Nets",
    4: "Charlotte Hornets",
    5: "Chicago Bulls",
    6: "Cleveland Cavaliers",
    7: "Detroit Pistons",
    8: "Indiana Pacers",
    9: "Miami Heat",
    10: "Milwaukee Bucks",
    11: "New York Knicks",
    12: "Orlando Magic",
    13: "Philadelphia 76ers",
    14: "Toronto Raptors",
    15: "Washington Wizards",
    16: "Dallas Mavericks",
    17: "Denver Nuggets",
    18: "Golden State Warriors",
    19: "Houston Rockets",
    20: "LA Clippers",
    21: "Los Angeles Lakers",
    22: "Memphis Grizzlies",
    23: "Minnesota Timberwolves",
    24: "New Orleans Pelicans",
    25: "Oklahoma City Thunder",
    26: "Phoenix Suns",
    27: "Portland Trail Blazers",
    28: "Sacramento Kings",
    29: "San Antonio Spurs",
    30: "Utah Jazz"
};